version: '2'

services:
  postgres:
    image: 'postgres:9.6'
    environment:
      POSTGRES_USER: 'tokyo_user'
      POSTGRES_PASSWORD: 'tokyo_password'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

volumes:
  postgres: