development:
  adapter: postgresql
  encoding: utf8
  database: tokyo_development
  username: tokyo_user
  password: tokyo_password
  pool: 5
  timeout: 5000
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: utf8
  database: tokyo_test
  username: tokyo_user
  password: tokyo_password
  pool: 5
  timeout: 5000
  host: localhost
  port: 5432